
modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

[[mods]] #mandatory
# The modid of the mod

modId="spaceandmore" #mandatory


version="${file.jarVersion}" #mandatory


displayName="PenguuJr's space and more!" #mandatory


logoFile="examplemod.png" #optional

credits="By PenguuJr" #optional


authors="Love, Cheese and small house plants" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
A Mod that's mainly about space but a little things here and there c:

'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.spaceandmore]] #optional
   
    modId="forge" #mandatory
    
    mandatory=true #mandatory
    
    versionRange="[40,)" #mandatory
    
    ordering="NONE"
    
    side="BOTH"
# Here's another dependency
[[dependencies.spaceandmore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
